FROM postgres:16.1

WORKDIR /app

# The PostgreSQL image runs all .sql, .sql.gz, or .sh scripts found in
# /docker-entrypoint-initdb.d/ upon initialization if the data directory is
# empty.
COPY internal/taskdb/migrations/20241007073735_init.up.sql /docker-entrypoint-initdb.d/
