version: '3'

services:
  postgres:
    container_name: task_pg
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - ./docker.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
    ports:
      - '8081:8081'
    depends_on:
      - postgres

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      WORKER_ADDRESS: worker
    depends_on:
      - coordinator
